"""initial telemetry schema

Revision ID: 01f66f1f81df
Revises: 
Create Date: 2026-04-25 18:23:08.660071
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import models  # noqa: F401  (provides models.JSONType used below)


# revision identifiers, used by Alembic.
revision: str = '01f66f1f81df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hardware_fingerprint', sa.String(length=128), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=False),
    sa.Column('chipset', sa.String(length=255), nullable=False),
    sa.Column('android_api', sa.Integer(), nullable=False),
    sa.Column('ram_gb', sa.Float(), nullable=False),
    sa.Column('shizuku_available', sa.Boolean(), nullable=False),
    sa.Column('agent_version', sa.String(length=32), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_hardware_fingerprint'), 'devices', ['hardware_fingerprint'], unique=True)
    op.create_index(op.f('ix_devices_last_seen'), 'devices', ['last_seen'], unique=False)
    op.create_table('device_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.Enum('install_started', 'install_done', 'install_failed', 'launch', 'error', 'heartbeat', name='device_event_type'), nullable=False),
    sa.Column('payload', models.JSONType(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_events_created_at'), 'device_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_device_events_device_id'), 'device_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_events_event_type'), 'device_events', ['event_type'], unique=False)
    op.create_table('installed_emulators',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('package_name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('install_method', sa.String(length=32), nullable=True),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'package_name', name='uq_device_package')
    )
    op.create_index(op.f('ix_installed_emulators_device_id'), 'installed_emulators', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_installed_emulators_device_id'), table_name='installed_emulators')
    op.drop_table('installed_emulators')
    op.drop_index(op.f('ix_device_events_event_type'), table_name='device_events')
    op.drop_index(op.f('ix_device_events_device_id'), table_name='device_events')
    op.drop_index(op.f('ix_device_events_created_at'), table_name='device_events')
    op.drop_table('device_events')
    op.drop_index(op.f('ix_devices_last_seen'), table_name='devices')
    op.drop_index(op.f('ix_devices_hardware_fingerprint'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
