"""add_os_hw_crash_save_telemetry

Revision ID: 51bf29c0c571
Revises: 01f66f1f81df
Create Date: 2026-04-27 09:29:56.479034
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import models  # noqa: F401  (provides models.JSONType used below)


# revision identifiers, used by Alembic.
revision: str = '51bf29c0c571'
down_revision: Union[str, None] = '01f66f1f81df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crash_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('emulator_package', sa.String(length=255), nullable=True),
    sa.Column('emulator_version_name', sa.String(length=64), nullable=True),
    sa.Column('emulator_version_code', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.String(length=64), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=True),
    sa.Column('duration_played_sec', sa.Integer(), nullable=True),
    sa.Column('crash_reason', sa.String(length=255), nullable=True),
    sa.Column('crash_signal', sa.String(length=32), nullable=True),
    sa.Column('rss_mb', sa.Integer(), nullable=True),
    sa.Column('pss_mb', sa.Integer(), nullable=True),
    sa.Column('stacktrace_hash', sa.String(length=64), nullable=True),
    sa.Column('tombstone_excerpt', sa.Text(), nullable=True),
    sa.Column('thermal_state', sa.String(length=32), nullable=True),
    sa.Column('battery_level', sa.Float(), nullable=True),
    sa.Column('battery_temperature_c', sa.Float(), nullable=True),
    sa.Column('free_ram_mb', sa.Integer(), nullable=True),
    sa.Column('page_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crash_events_device_id'), 'crash_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_crash_events_timestamp'), 'crash_events', ['timestamp'], unique=False)
    op.add_column('devices', sa.Column('manufacturer', sa.String(length=128), nullable=True))
    op.add_column('devices', sa.Column('model', sa.String(length=128), nullable=True))
    op.add_column('devices', sa.Column('android_release', sa.String(length=32), nullable=True))
    op.add_column('devices', sa.Column('soc_vendor', sa.String(length=128), nullable=True))
    op.add_column('devices', sa.Column('soc_chip', sa.String(length=128), nullable=True))
    op.add_column('devices', sa.Column('gpu_family', sa.String(length=128), nullable=True))
    op.add_column('devices', sa.Column('page_size', sa.Integer(), nullable=True))
    op.add_column('devices', sa.Column('ram_mb', sa.Integer(), nullable=True))
    op.add_column('devices', sa.Column('shizuku_version', sa.Integer(), nullable=True))
    op.add_column('devices', sa.Column('is_rooted', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('devices', sa.Column('has_analog_sticks', sa.Boolean(), nullable=True))
    op.add_column('devices', sa.Column('controller_layout', sa.String(length=32), nullable=True))
    op.add_column('devices', sa.Column('vendor_shell_packages', models.JSONType(), nullable=True))
    op.add_column('devices', sa.Column('thermal_state', sa.String(length=32), nullable=True))
    op.add_column('devices', sa.Column('battery_level', sa.Float(), nullable=True))
    op.add_column('devices', sa.Column('battery_temperature_c', sa.Float(), nullable=True))
    op.add_column('devices', sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('devices', sa.Column('last_known_ip', sa.String(length=64), nullable=True))
    op.add_column('devices', sa.Column('save_events_24h', models.JSONType(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'save_events_24h')
    op.drop_column('devices', 'last_known_ip')
    op.drop_column('devices', 'last_heartbeat_at')
    op.drop_column('devices', 'battery_temperature_c')
    op.drop_column('devices', 'battery_level')
    op.drop_column('devices', 'thermal_state')
    op.drop_column('devices', 'vendor_shell_packages')
    op.drop_column('devices', 'controller_layout')
    op.drop_column('devices', 'has_analog_sticks')
    op.drop_column('devices', 'is_rooted')
    op.drop_column('devices', 'shizuku_version')
    op.drop_column('devices', 'ram_mb')
    op.drop_column('devices', 'page_size')
    op.drop_column('devices', 'gpu_family')
    op.drop_column('devices', 'soc_chip')
    op.drop_column('devices', 'soc_vendor')
    op.drop_column('devices', 'android_release')
    op.drop_column('devices', 'model')
    op.drop_column('devices', 'manufacturer')
    op.drop_index(op.f('ix_crash_events_timestamp'), table_name='crash_events')
    op.drop_index(op.f('ix_crash_events_device_id'), table_name='crash_events')
    op.drop_table('crash_events')
    # ### end Alembic commands ###
